### ISSUE TITLE
[BUG]: I AM HAVE BUG

### ISSUE THREAD

**Issue by RobynLlama** [LethalModding/Radar_Ident_QuickSwitch#16]
### Installation Method

Friend told me to extract it

### What happened?

bug!

### What did you do?

1. Bug!!!!

### Version

v45

### What OS are you running?

Mac

### Relevant log output

```PowerShell
WAAAH BUG
```

### Code of Conduct

- [x] #17

**Comment by AlbinoGeek** [comment]
We do not support `v45` anymore.
